insert into Yy values("0000001", "3R2", "Angelic Sphere", "http://localhost:8080/resource/music/Angelic Sphere.mp3", "http://localhost:8080/resource/music/Angelic Sphere.jpg", 0);
insert into Yy values("0000002", "3R2", "Farewell", "http://localhost:8080/resource/music/Farewell.mp3", "http://localhost:8080/resource/music/Farewell.jpg", 0);
insert into Yy values("0000003", "Adele", "Rolling In The Deep", "http://localhost:8080/resource/music/Rolling In The Deep.mp3", "http://localhost:8080/resource/music/Rolling In The Deep.jpg", 0);
insert into Yy values("0000004", "Ahrix", "Left Behind", "http://localhost:8080/resource/music/Left Behind.mp3", "http://localhost:8080/resource/music/Left Behind.jpg", 0);
insert into Yy values("0000005", "Ahxello", "Revolution", "http://localhost:8080/resource/music/Revolution.mp3", "http://localhost:8080/resource/music/Revolution.jpg", 0);
insert into Yy values("0000006", "Ahxello", "Sky High", "http://localhost:8080/resource/music/Sky High.mp3", "http://localhost:8080/resource/music/Sky High.jpg", 0);
insert into Yy values("0000007", "Ahxello", "Tomorrow", "http://localhost:8080/resource/music/Tomorrow.mp3", "http://localhost:8080/resource/music/Tomorrow.jpg", 0);
insert into Yy values("0000008", "Alan Walker", "Fade", "http://localhost:8080/resource/music/Fade.mp3", "http://localhost:8080/resource/music/Fade.jpg", 0);
insert into Yy values("0000009", "Alan Walker", "Faded", "http://localhost:8080/resource/music/Faded.mp3", "http://localhost:8080/resource/music/Faded.jpg", 0);
insert into Yy values("0000010", "Alan Walker", "Spectre", "http://localhost:8080/resource/music/Spectre.mp3", "http://localhost:8080/resource/music/Spectre.jpg", 0);
insert into Yy values("0000011", "Alan Walker Noonie Bao", "Alone", "http://localhost:8080/resource/music/Alone.mp3", "http://localhost:8080/resource/music/Alone.jpg", 0);
insert into Yy values("0000012", "Anan Ryoko", "Refrain", "http://localhost:8080/resource/music/Refrain.mp3", "http://localhost:8080/resource/music/Refrain.png", 0);
insert into Yy values("0000013", "AniFace", "Cold Rain", "http://localhost:8080/resource/music/Cold Rain.mp3", "http://localhost:8080/resource/music/Cold Rain.jpg", 0);
insert into Yy values("0000014", "Approaching Nirvana", "305", "http://localhost:8080/resource/music/305.mp3", "http://localhost:8080/resource/music/305.jpg", 0);
insert into Yy values("0000015", "Approaching Nirvana", "You", "http://localhost:8080/resource/music/You.mp3", "http://localhost:8080/resource/music/You.png", 0);
insert into Yy values("0000016", "Asher Monroe", "Here With You", "http://localhost:8080/resource/music/Here With You.mp3", "http://localhost:8080/resource/music/Here With You.jpg", 0);
insert into Yy values("0000017", "Atchorite", "Kimi Wo Omou Melodi", "http://localhost:8080/resource/music/Kimi Wo Omou Melodi.mp3", "http://localhost:8080/resource/music/Kimi Wo Omou Melodi.jpg", 0);
insert into Yy values("0000018", "Audio Highs", "男子高校生とチェイス", "http://localhost:8080/resource/music/男子高校生とチェイス.mp3", "http://localhost:8080/resource/music/男子高校生とチェイス.png", 0);
insert into Yy values("0000019", "Audio Highs", "男子高校生と文学少女", "http://localhost:8080/resource/music/男子高校生と文学少女.mp3", "http://localhost:8080/resource/music/男子高校生と文学少女.png", 0);
insert into Yy values("0000020", "Audiomachine", "Breath and Life", "http://localhost:8080/resource/music/Breath and Life.mp3", "http://localhost:8080/resource/music/Breath and Life.png", 0);
insert into Yy values("0000021", "Axero", "Downtown", "http://localhost:8080/resource/music/Downtown.mp3", "http://localhost:8080/resource/music/Downtown.jpg", 0);
insert into Yy values("0000022", "Axero", "River", "http://localhost:8080/resource/music/River.mp3", "http://localhost:8080/resource/music/River.jpg", 0);
insert into Yy values("0000023", "Axlance Luka Krajina", "Dreams (Original Mix)", "http://localhost:8080/resource/music/Dreams (Original Mix).mp3", "http://localhost:8080/resource/music/Dreams (Original Mix).jpg", 0);
insert into Yy values("0000024", "BeaTsGOy", "Piano Beat", "http://localhost:8080/resource/music/Piano Beat.mp3", "http://localhost:8080/resource/music/Piano Beat.jpg", 0);
insert into Yy values("0000025", "Blaxy Girls", "If You Feel My Love", "http://localhost:8080/resource/music/If You Feel My Love.mp3", "http://localhost:8080/resource/music/If You Feel My Love.jpg", 0);
insert into Yy values("0000026", "Blue", "U Make Me Wanna", "http://localhost:8080/resource/music/U Make Me Wanna.mp3", "http://localhost:8080/resource/music/U Make Me Wanna.jpg", 0);
insert into Yy values("0000027", "Brian Crain", "canon in d", "http://localhost:8080/resource/music/canon in d.mp3", "http://localhost:8080/resource/music/canon in d.png", 0);
insert into Yy values("0000028", "CAGNET", "Here We Are Again", "http://localhost:8080/resource/music/Here We Are Again.mp3", "http://localhost:8080/resource/music/Here We Are Again.jpg", 0);
insert into Yy values("0000029", "Cam Kelley", "Sketch Plane", "http://localhost:8080/resource/music/Sketch Plane.mp3", "http://localhost:8080/resource/music/Sketch Plane.png", 0);
insert into Yy values("0000030", "Candy_Wind", "繁华的风景", "http://localhost:8080/resource/music/繁华的风景.mp3", "http://localhost:8080/resource/music/繁华的风景.jpg", 0);
insert into Yy values("0000031", "Candy_Wind", "青空", "http://localhost:8080/resource/music/青空.mp3", "http://localhost:8080/resource/music/青空.jpg", 0);
insert into Yy values("0000032", "Capo Productions", "Aurora", "http://localhost:8080/resource/music/Aurora.mp3", "http://localhost:8080/resource/music/Aurora.jpg", 0);
insert into Yy values("0000033", "Capo Productions", "Journey", "http://localhost:8080/resource/music/Journey.mp3", "http://localhost:8080/resource/music/Journey.jpg", 0);
insert into Yy values("0000034", "Capo Productions", "Oblivion", "http://localhost:8080/resource/music/Oblivion.mp3", "http://localhost:8080/resource/music/Oblivion.jpg", 0);
insert into Yy values("0000035", "Cargo VINAI SCNDL", "Frontier (Cargo Remix)", "http://localhost:8080/resource/music/Frontier (Cargo Remix).mp3", "http://localhost:8080/resource/music/Frontier (Cargo Remix).jpg", 0);
insert into Yy values("0000036", "CelDro", "Aspire", "http://localhost:8080/resource/music/Aspire.mp3", "http://localhost:8080/resource/music/Aspire.jpg", 0);
insert into Yy values("0000037", "Charlie Puth Selena Gomez", "We Don't Talk Anymore", "http://localhost:8080/resource/music/We Don't Talk Anymore.mp3", "http://localhost:8080/resource/music/We Don't Talk Anymore.jpg", 0);
insert into Yy values("0000038", "Chasjam", "Zippo", "http://localhost:8080/resource/music/Zippo.mp3", "http://localhost:8080/resource/music/Zippo.jpg", 0);
insert into Yy values("0000039", "Christina Perri", "A Thousand Years (1)", "http://localhost:8080/resource/music/A Thousand Years (1).mp3", "http://localhost:8080/resource/music/A Thousand Years (1).jpg", 0);
insert into Yy values("0000040", "Clarv", "Freedom", "http://localhost:8080/resource/music/Freedom.mp3", "http://localhost:8080/resource/music/Freedom.jpg", 0);
insert into Yy values("0000041", "Clean Bandit Jess Glynne", "Rather Be (Instrumental)", "http://localhost:8080/resource/music/Rather Be (Instrumental).mp3", "http://localhost:8080/resource/music/Rather Be (Instrumental).jpg", 0);
insert into Yy values("0000042", "CLIFF EDGE", "Endless Tears", "http://localhost:8080/resource/music/Endless Tears.mp3", "http://localhost:8080/resource/music/Endless Tears.png", 0);
insert into Yy values("0000043", "DAISHI DANCE", "if...", "http://localhost:8080/resource/music/if....mp3", "http://localhost:8080/resource/music/if....png", 0);
insert into Yy values("0000044", "David Garrett", "Peer Gynt", "http://localhost:8080/resource/music/Peer Gynt.mp3", "http://localhost:8080/resource/music/Peer Gynt.jpg", 0);
insert into Yy values("0000045", "Delacey", "Dream It Possible", "http://localhost:8080/resource/music/Dream It Possible.mp3", "http://localhost:8080/resource/music/Dream It Possible.jpg", 0);
insert into Yy values("0000046", "Dennis Kuo", "Ever Eternity", "http://localhost:8080/resource/music/Ever Eternity.mp3", "http://localhost:8080/resource/music/Ever Eternity.jpg", 0);
insert into Yy values("0000047", "DEPAPEPE", "禁じられた恋", "http://localhost:8080/resource/music/禁じられた恋.mp3", "http://localhost:8080/resource/music/禁じられた恋.png", 0);
insert into Yy values("0000048", "Diana Boncheva", "Beethoven Virus", "http://localhost:8080/resource/music/Beethoven Virus.mp3", "http://localhost:8080/resource/music/Beethoven Virus.png", 0);
insert into Yy values("0000049", "Diana Boncheva", "Purple Passion", "http://localhost:8080/resource/music/Purple Passion.mp3", "http://localhost:8080/resource/music/Purple Passion.png", 0);
insert into Yy values("0000050", "DiESi", "Scorching Sun（Original Mix）", "http://localhost:8080/resource/music/Scorching Sun（Original Mix）.mp3", "http://localhost:8080/resource/music/Scorching Sun（Original Mix）.jpg", 0);
insert into Yy values("0000051", "DiESi", "清丶风（DiESi Remix）", "http://localhost:8080/resource/music/清丶风（DiESi Remix）.mp3", "http://localhost:8080/resource/music/清丶风（DiESi Remix）.jpg", 0);
insert into Yy values("0000052", "Different Heaven", "Nekozilla", "http://localhost:8080/resource/music/Nekozilla.mp3", "http://localhost:8080/resource/music/Nekozilla.jpg", 0);
insert into Yy values("0000053", "Distrion Electro-Light", "Rubik", "http://localhost:8080/resource/music/Rubik.mp3", "http://localhost:8080/resource/music/Rubik.jpg", 0);
insert into Yy values("0000054", "DJ Daniel Kim", "Pop Danthology 2012", "http://localhost:8080/resource/music/Pop Danthology 2012.mp3", "http://localhost:8080/resource/music/Pop Danthology 2012.jpg", 0);
insert into Yy values("0000055", "DJ Okawari", "Flower Dance", "http://localhost:8080/resource/music/Flower Dance.mp3", "http://localhost:8080/resource/music/Flower Dance.png", 0);
insert into Yy values("0000056", "DJ Okawari", "Luv Letter", "http://localhost:8080/resource/music/Luv Letter.mp3", "http://localhost:8080/resource/music/Luv Letter.png", 0);
insert into Yy values("0000057", "DJ Siesta", "Another Day", "http://localhost:8080/resource/music/Another Day.mp3", "http://localhost:8080/resource/music/Another Day.jpg", 0);
insert into Yy values("0000058", "DJ SLY", "いのちの名前 ~ジブリ・メドレー~", "http://localhost:8080/resource/music/いのちの名前 ~ジブリ・メドレー~.mp3", "http://localhost:8080/resource/music/いのちの名前 ~ジブリ・メドレー~.png", 0);
insert into Yy values("0000059", "DJ Soviet", "Royal Poison-［Original Mix］-", "http://localhost:8080/resource/music/Royal Poison-［Original Mix］-.mp3", "http://localhost:8080/resource/music/Royal Poison-［Original Mix］-.png", 0);
insert into Yy values("0000060", "Dogena", "Angel ( Radio Edit )", "http://localhost:8080/resource/music/Angel ( Radio Edit ).mp3", "http://localhost:8080/resource/music/Angel ( Radio Edit ).jpg", 0);
insert into Yy values("0000061", "Dreamtale", "Intro： The Dawn", "http://localhost:8080/resource/music/Intro： The Dawn.mp3", "http://localhost:8080/resource/music/Intro： The Dawn.jpg", 0);
insert into Yy values("0000062", "Drop Tower", "If Only You", "http://localhost:8080/resource/music/If Only You.mp3", "http://localhost:8080/resource/music/If Only You.jpg", 0);
insert into Yy values("0000063", "EARTHBOUND PAPAS", "Metal Hypnotized", "http://localhost:8080/resource/music/Metal Hypnotized.mp3", "http://localhost:8080/resource/music/Metal Hypnotized.jpg", 0);
insert into Yy values("0000064", "Ed Sheeran", "Shape of You", "http://localhost:8080/resource/music/Shape of You.mp3", "http://localhost:8080/resource/music/Shape of You.jpg", 0);
insert into Yy values("0000065", "Elliot Hsu", "Utopia", "http://localhost:8080/resource/music/Utopia.mp3", "http://localhost:8080/resource/music/Utopia.jpg", 0);
insert into Yy values("0000066", "EnV", "Paladin", "http://localhost:8080/resource/music/Paladin.mp3", "http://localhost:8080/resource/music/Paladin.jpg", 0);
insert into Yy values("0000067", "EnV", "Pearlescent", "http://localhost:8080/resource/music/Pearlescent.mp3", "http://localhost:8080/resource/music/Pearlescent.jpg", 0);
insert into Yy values("0000068", "FadeX", "Vivant", "http://localhost:8080/resource/music/Vivant.mp3", "http://localhost:8080/resource/music/Vivant.jpg", 0);
insert into Yy values("0000069", "Fathoms  MaHi", "Uncommon Journey (Original Mix)", "http://localhost:8080/resource/music/Uncommon Journey (Original Mix).mp3", "http://localhost:8080/resource/music/Uncommon Journey (Original Mix).jpg", 0);
insert into Yy values("0000070", "Feint", "Face Down (Original Mix)", "http://localhost:8080/resource/music/Face Down (Original Mix).mp3", "http://localhost:8080/resource/music/Face Down (Original Mix).jpg", 0);
insert into Yy values("0000071", "FEWZ", "Levitate", "http://localhost:8080/resource/music/Levitate.mp3", "http://localhost:8080/resource/music/Levitate.jpg", 0);
insert into Yy values("0000072", "Fly Project", "Toca Toca (Radio Edit)", "http://localhost:8080/resource/music/Toca Toca (Radio Edit).mp3", "http://localhost:8080/resource/music/Toca Toca (Radio Edit).jpg", 0);
insert into Yy values("0000073", "Foxtail-Grass Studio", "Cattleya", "http://localhost:8080/resource/music/Cattleya.mp3", "http://localhost:8080/resource/music/Cattleya.png", 0);
insert into Yy values("0000074", "Foxtail-Grass Studio", "Lupinus", "http://localhost:8080/resource/music/Lupinus.mp3", "http://localhost:8080/resource/music/Lupinus.png", 0);
insert into Yy values("0000075", "Foxtail-Grass Studio", "Mountain Journey", "http://localhost:8080/resource/music/Mountain Journey.mp3", "http://localhost:8080/resource/music/Mountain Journey.png", 0);
insert into Yy values("0000076", "Foxtail-Grass Studio", "sora no mukou", "http://localhost:8080/resource/music/sora no mukou.mp3", "http://localhost:8080/resource/music/sora no mukou.jpg", 0);
insert into Yy values("0000077", "Foxtail-Grass Studio", "瞳の中で踊り踊られ", "http://localhost:8080/resource/music/瞳の中で踊り踊られ.mp3", "http://localhost:8080/resource/music/瞳の中で踊り踊られ.jpg", 0);
insert into Yy values("0000078", "Foxtail-Grass Studio", "髪飾りの記憶", "http://localhost:8080/resource/music/髪飾りの記憶.mp3", "http://localhost:8080/resource/music/髪飾りの記憶.png", 0);
insert into Yy values("0000079", "Frankmusik", "Wrecking Ball", "http://localhost:8080/resource/music/Wrecking Ball.mp3", "http://localhost:8080/resource/music/Wrecking Ball.jpg", 0);
insert into Yy values("0000080", "GARNiDELiA", "極楽浄土", "http://localhost:8080/resource/music/極楽浄土.mp3", "http://localhost:8080/resource/music/極楽浄土.jpg", 0);
insert into Yy values("0000081", "GEMINI", "Cloud 9", "http://localhost:8080/resource/music/Cloud 9.mp3", "http://localhost:8080/resource/music/Cloud 9.jpg", 0);
insert into Yy values("0000082", "Giulia", "Ce Frumoasa E Iubirea", "http://localhost:8080/resource/music/Ce Frumoasa E Iubirea.mp3", "http://localhost:8080/resource/music/Ce Frumoasa E Iubirea.png", 0);
insert into Yy values("0000083", "Grand Thaw", "Freezing Floweret", "http://localhost:8080/resource/music/Freezing Floweret.mp3", "http://localhost:8080/resource/music/Freezing Floweret.jpg", 0);
insert into Yy values("0000084", "Grand Thaw", "Grad Erlija", "http://localhost:8080/resource/music/Grad Erlija.mp3", "http://localhost:8080/resource/music/Grad Erlija.jpg", 0);
insert into Yy values("0000085", "Greyson Chance", "Summertrain", "http://localhost:8080/resource/music/Summertrain.mp3", "http://localhost:8080/resource/music/Summertrain.jpg", 0);
insert into Yy values("0000086", "Hallo", "涼風", "http://localhost:8080/resource/music/涼風.mp3", "http://localhost:8080/resource/music/涼風.png", 0);
insert into Yy values("0000087", "HAZZY", "月の雫", "http://localhost:8080/resource/music/月の雫.mp3", "http://localhost:8080/resource/music/月の雫.png", 0);
insert into Yy values("0000088", "himmel", "Code Paradiso", "http://localhost:8080/resource/music/Code Paradiso.mp3", "http://localhost:8080/resource/music/Code Paradiso.jpg", 0);
insert into Yy values("0000089", "himmel", "Empyrean", "http://localhost:8080/resource/music/Empyrean.mp3", "http://localhost:8080/resource/music/Empyrean.jpg", 0);
insert into Yy values("0000090", "himmel", "千之缘（off vocal）", "http://localhost:8080/resource/music/千之缘（off vocal）.mp3", "http://localhost:8080/resource/music/千之缘（off vocal）.jpg", 0);
insert into Yy values("0000091", "himmel", "樱华彩（off vocal）", "http://localhost:8080/resource/music/樱华彩（off vocal）.mp3", "http://localhost:8080/resource/music/樱华彩（off vocal）.jpg", 0);
insert into Yy values("0000092", "Hinkik", "Ena", "http://localhost:8080/resource/music/Ena.mp3", "http://localhost:8080/resource/music/Ena.jpg", 0);
insert into Yy values("0000093", "Hinkik", "Invaders (Original Mix)", "http://localhost:8080/resource/music/Invaders (Original Mix).mp3", "http://localhost:8080/resource/music/Invaders (Original Mix).jpg", 0);
insert into Yy values("0000094", "Hinkik", "Outbreaker", "http://localhost:8080/resource/music/Outbreaker.mp3", "http://localhost:8080/resource/music/Outbreaker.jpg", 0);
insert into Yy values("0000095", "Hollywood Undead", "Levitate", "http://localhost:8080/resource/music/Levitate.mp3", "http://localhost:8080/resource/music/Levitate.jpg", 0);
insert into Yy values("0000096", "HOPE-T", "夜闯秋名山（弹幕歌词版）", "http://localhost:8080/resource/music/夜闯秋名山（弹幕歌词版）.mp3", "http://localhost:8080/resource/music/夜闯秋名山（弹幕歌词版）.jpg", 0);
insert into Yy values("0000097", "Icona Pop", "I Love It", "http://localhost:8080/resource/music/I Love It.mp3", "http://localhost:8080/resource/music/I Love It.jpg", 0);
insert into Yy values("0000098", "Immediate Music", "Tales of the Electric Romeo", "http://localhost:8080/resource/music/Tales of the Electric Romeo.mp3", "http://localhost:8080/resource/music/Tales of the Electric Romeo.jpg", 0);
insert into Yy values("0000099", "iris", "Letter", "http://localhost:8080/resource/music/Letter.mp3", "http://localhost:8080/resource/music/Letter.png", 0);
insert into Yy values("0000100", "Jiaye", "Tony Igy-Astronomia（Jiaye remix）", "http://localhost:8080/resource/music/Tony Igy-Astronomia（Jiaye remix）.mp3", "http://localhost:8080/resource/music/Tony Igy-Astronomia（Jiaye remix）.jpg", 0);
insert into Yy values("0000101", "Jim Brickman", "Serenade", "http://localhost:8080/resource/music/Serenade.mp3", "http://localhost:8080/resource/music/Serenade.jpg", 0);
insert into Yy values("0000102", "Jim Yosef Alex Skrindo", "Passion", "http://localhost:8080/resource/music/Passion.mp3", "http://localhost:8080/resource/music/Passion.jpg", 0);
insert into Yy values("0000103", "Joohyun Gil", "Autumn's Wind", "http://localhost:8080/resource/music/Autumn's Wind.mp3", "http://localhost:8080/resource/music/Autumn's Wind.jpg", 0);
insert into Yy values("0000104", "Juliet", "モトカレ (Instrumental)", "http://localhost:8080/resource/music/モトカレ (Instrumental).mp3", "http://localhost:8080/resource/music/モトカレ (Instrumental).png", 0);
insert into Yy values("0000105", "July", "In Love", "http://localhost:8080/resource/music/In Love.mp3", "http://localhost:8080/resource/music/In Love.png", 0);
insert into Yy values("0000106", "July", "My Soul", "http://localhost:8080/resource/music/My Soul.mp3", "http://localhost:8080/resource/music/My Soul.png", 0);
insert into Yy values("0000107", "July", "사랑에 베이다", "http://localhost:8080/resource/music/사랑에 베이다.mp3", "http://localhost:8080/resource/music/사랑에 베이다.png", 0);
insert into Yy values("0000108", "Junk", "Fire Strike", "http://localhost:8080/resource/music/Fire Strike.mp3", "http://localhost:8080/resource/music/Fire Strike.jpg", 0);
insert into Yy values("0000109", "K-391", "Electro House 2012", "http://localhost:8080/resource/music/Electro House 2012.mp3", "http://localhost:8080/resource/music/Electro House 2012.jpg", 0);
insert into Yy values("0000110", "K-391", "Summertime", "http://localhost:8080/resource/music/Summertime.mp3", "http://localhost:8080/resource/music/Summertime.jpg", 0);
insert into Yy values("0000111", "Ken Arai", "NEXT TO YOU -Rhodes Version-", "http://localhost:8080/resource/music/NEXT TO YOU -Rhodes Version-.mp3", "http://localhost:8080/resource/music/NEXT TO YOU -Rhodes Version-.jpg", 0);
insert into Yy values("0000112", "Kestutis K", "Another Day", "http://localhost:8080/resource/music/Another Day.mp3", "http://localhost:8080/resource/music/Another Day.jpg", 0);
insert into Yy values("0000113", "KSHMR", "Leviathan (Original Mix)", "http://localhost:8080/resource/music/Leviathan (Original Mix).mp3", "http://localhost:8080/resource/music/Leviathan (Original Mix).jpg", 0);
insert into Yy values("0000114", "Kyle Xian", "めざせポケモンマスター ~ 目标是宝可梦大师（精灵宝可梦 无印OP）（Cover 松本梨香）", "http://localhost:8080/resource/music/めざせポケモンマスター ~ 目标是宝可梦大师（精灵宝可梦 无印OP）（Cover 松本梨香）.mp3", "http://localhost:8080/resource/music/めざせポケモンマスター ~ 目标是宝可梦大师（精灵宝可梦 无印OP）（Cover 松本梨香）.jpg", 0);
insert into Yy values("0000115", "Kyle Xian", "宠物小精灵（精灵宝可梦 无印 中版OP）（Cover 陈浩民）", "http://localhost:8080/resource/music/宠物小精灵（精灵宝可梦 无印 中版OP）（Cover 陈浩民）.mp3", "http://localhost:8080/resource/music/宠物小精灵（精灵宝可梦 无印 中版OP）（Cover 陈浩民）.jpg", 0);
insert into Yy values("0000116", "L3V3LS", "All In", "http://localhost:8080/resource/music/All In.mp3", "http://localhost:8080/resource/music/All In.jpg", 0);
insert into Yy values("0000117", "L3V3LS", "Soaring High", "http://localhost:8080/resource/music/Soaring High.mp3", "http://localhost:8080/resource/music/Soaring High.jpg", 0);
insert into Yy values("0000118", "Laura Shigihara", "Brainiac Maniac", "http://localhost:8080/resource/music/Brainiac Maniac.mp3", "http://localhost:8080/resource/music/Brainiac Maniac.png", 0);
insert into Yy values("0000119", "Laura Shigihara", "Crazy Dave (Intro Theme)", "http://localhost:8080/resource/music/Crazy Dave (Intro Theme).mp3", "http://localhost:8080/resource/music/Crazy Dave (Intro Theme).png", 0);
insert into Yy values("0000120", "Laura Shigihara", "Grasswalk", "http://localhost:8080/resource/music/Grasswalk.mp3", "http://localhost:8080/resource/music/Grasswalk.png", 0);
insert into Yy values("0000121", "Laura Shigihara", "Graze the Roof", "http://localhost:8080/resource/music/Graze the Roof.mp3", "http://localhost:8080/resource/music/Graze the Roof.png", 0);
insert into Yy values("0000122", "Laura Shigihara", "Grazy Dave (Intro Theme)", "http://localhost:8080/resource/music/Grazy Dave (Intro Theme).mp3", "http://localhost:8080/resource/music/Grazy Dave (Intro Theme).png", 0);
insert into Yy values("0000123", "Laura Shigihara", "Loonboon", "http://localhost:8080/resource/music/Loonboon.mp3", "http://localhost:8080/resource/music/Loonboon.png", 0);
insert into Yy values("0000124", "Laura Shigihara", "Ultimate Battle", "http://localhost:8080/resource/music/Ultimate Battle.mp3", "http://localhost:8080/resource/music/Ultimate Battle.png", 0);
insert into Yy values("0000125", "Lightscape", "Recollection", "http://localhost:8080/resource/music/Recollection.mp3", "http://localhost:8080/resource/music/Recollection.jpg", 0);
insert into Yy values("0000126", "Lindsey Stirling", "Master of Tides", "http://localhost:8080/resource/music/Master of Tides.mp3", "http://localhost:8080/resource/music/Master of Tides.jpg", 0);
insert into Yy values("0000127", "Little West", "Breeze", "http://localhost:8080/resource/music/Breeze.mp3", "http://localhost:8080/resource/music/Breeze.png", 0);
insert into Yy values("0000128", "Little West", "Lost In My View", "http://localhost:8080/resource/music/Lost In My View.mp3", "http://localhost:8080/resource/music/Lost In My View.png", 0);
insert into Yy values("0000129", "m-taku", "Komorebi", "http://localhost:8080/resource/music/Komorebi.mp3", "http://localhost:8080/resource/music/Komorebi.jpg", 0);
insert into Yy values("0000130", "MaHi", "Lucky Charms", "http://localhost:8080/resource/music/Lucky Charms.mp3", "http://localhost:8080/resource/music/Lucky Charms.jpg", 0);
insert into Yy values("0000131", "majiko", "アイロニ", "http://localhost:8080/resource/music/アイロニ.mp3", "http://localhost:8080/resource/music/アイロニ.jpg", 0);
insert into Yy values("0000132", "majiko", "アストロノーツ", "http://localhost:8080/resource/music/アストロノーツ.mp3", "http://localhost:8080/resource/music/アストロノーツ.jpg", 0);
insert into Yy values("0000133", "majiko れをる", "Fantastic Baby", "http://localhost:8080/resource/music/Fantastic Baby.mp3", "http://localhost:8080/resource/music/Fantastic Baby.jpg", 0);
insert into Yy values("0000134", "Mako", "Beam(Original)", "http://localhost:8080/resource/music/Beam(Original).mp3", "http://localhost:8080/resource/music/Beam(Original).jpg", 0);
insert into Yy values("0000135", "Mark Petrie", "Go Time", "http://localhost:8080/resource/music/Go Time.mp3", "http://localhost:8080/resource/music/Go Time.jpg", 0);
insert into Yy values("0000136", "Mark Pride", "River Flows In You (Original Mix)", "http://localhost:8080/resource/music/River Flows In You (Original Mix).mp3", "http://localhost:8080/resource/music/River Flows In You (Original Mix).png", 0);
insert into Yy values("0000137", "Martin Garrix", "Animals(2)", "http://localhost:8080/resource/music/Animals(2).mp3", "http://localhost:8080/resource/music/Animals(2).png", 0);
insert into Yy values("0000138", "Martin Garrix", "Animals", "http://localhost:8080/resource/music/Animals.mp3", "http://localhost:8080/resource/music/Animals.jpg", 0);
insert into Yy values("0000139", "Matteo", "Panama", "http://localhost:8080/resource/music/Panama.mp3", "http://localhost:8080/resource/music/Panama.jpg", 0);
insert into Yy values("0000140", "MetroGnome", "One More Night (MetroGnome Electro Remix)", "http://localhost:8080/resource/music/One More Night (MetroGnome Electro Remix).mp3", "http://localhost:8080/resource/music/One More Night (MetroGnome Electro Remix).jpg", 0);
insert into Yy values("0000141", "Mich", "Skyland", "http://localhost:8080/resource/music/Skyland.mp3", "http://localhost:8080/resource/music/Skyland.jpg", 0);
insert into Yy values("0000142", "Michael Giacchino Lalo Schifrin", "Light The Fuse", "http://localhost:8080/resource/music/Light The Fuse.mp3", "http://localhost:8080/resource/music/Light The Fuse.jpg", 0);
insert into Yy values("0000143", "miu-clips", "絆", "http://localhost:8080/resource/music/絆.mp3", "http://localhost:8080/resource/music/絆.png", 0);
insert into Yy values("0000144", "MKJ", "Time (Official)", "http://localhost:8080/resource/music/Time (Official).mp3", "http://localhost:8080/resource/music/Time (Official).jpg", 0);
insert into Yy values("0000145", "Muse", "Butterflies & Hurricanes", "http://localhost:8080/resource/music/Butterflies & Hurricanes.mp3", "http://localhost:8080/resource/music/Butterflies & Hurricanes.jpg", 0);
insert into Yy values("0000146", "NANASE", "DEAR~", "http://localhost:8080/resource/music/DEAR~.mp3", "http://localhost:8080/resource/music/DEAR~.jpg", 0);
insert into Yy values("0000147", "Nega music project", "My Thai (thai Beach Remake)", "http://localhost:8080/resource/music/My Thai (thai Beach Remake).mp3", "http://localhost:8080/resource/music/My Thai (thai Beach Remake).png", 0);
insert into Yy values("0000148", "NGC 3.14", "Beloved Tomboyish Daughter (NGC 3​.​14 Remix)", "http://localhost:8080/resource/music/Beloved Tomboyish Daughter (NGC 3​.​14 Remix).mp3", "http://localhost:8080/resource/music/Beloved Tomboyish Daughter (NGC 3​.​14 Remix).jpg", 0);
insert into Yy values("0000149", "Nicholas Cheung", "Only Wish", "http://localhost:8080/resource/music/Only Wish.mp3", "http://localhost:8080/resource/music/Only Wish.png", 0);
insert into Yy values("0000150", "Nightwish", "Last Of The Wilds", "http://localhost:8080/resource/music/Last Of The Wilds.mp3", "http://localhost:8080/resource/music/Last Of The Wilds.jpg", 0);
insert into Yy values("0000151", "Noicybino", "Farewell", "http://localhost:8080/resource/music/Farewell.mp3", "http://localhost:8080/resource/music/Farewell.jpg", 0);
insert into Yy values("0000152", "One Direction", "What Makes You Beautiful", "http://localhost:8080/resource/music/What Makes You Beautiful.mp3", "http://localhost:8080/resource/music/What Makes You Beautiful.jpg", 0);
insert into Yy values("0000153", "OneRepublic", "Counting Stars", "http://localhost:8080/resource/music/Counting Stars.mp3", "http://localhost:8080/resource/music/Counting Stars.jpg", 0);
insert into Yy values("0000154", "Otokaze", "Mallow Flower", "http://localhost:8080/resource/music/Mallow Flower.mp3", "http://localhost:8080/resource/music/Mallow Flower.png", 0);
insert into Yy values("0000155", "Otokaze", "Save the flavor Part3 -Insturmental version-", "http://localhost:8080/resource/music/Save the flavor Part3 -Insturmental version-.mp3", "http://localhost:8080/resource/music/Save the flavor Part3 -Insturmental version-.png", 0);
insert into Yy values("0000156", "Otokaze", "夏恋", "http://localhost:8080/resource/music/夏恋.mp3", "http://localhost:8080/resource/music/夏恋.png", 0);
insert into Yy values("0000157", "Otokaze", "帰路 - KaeriMichi -", "http://localhost:8080/resource/music/帰路 - KaeriMichi -.mp3", "http://localhost:8080/resource/music/帰路 - KaeriMichi -.png", 0);
insert into Yy values("0000158", "OUTER SPACE", "Travel (Original Mix)", "http://localhost:8080/resource/music/Travel (Original Mix).mp3", "http://localhost:8080/resource/music/Travel (Original Mix).png", 0);
insert into Yy values("0000159", "Parov Stelar", "All Night", "http://localhost:8080/resource/music/All Night.mp3", "http://localhost:8080/resource/music/All Night.jpg", 0);
insert into Yy values("0000160", "Pegboard Nerds", "Disconnected", "http://localhost:8080/resource/music/Disconnected.mp3", "http://localhost:8080/resource/music/Disconnected.jpg", 0);
insert into Yy values("0000161", "Pharrell Williams", "Happy", "http://localhost:8080/resource/music/Happy.mp3", "http://localhost:8080/resource/music/Happy.jpg", 0);
insert into Yy values("0000162", "Philter", "Adventure Time", "http://localhost:8080/resource/music/Adventure Time.mp3", "http://localhost:8080/resource/music/Adventure Time.jpg", 0);
insert into Yy values("0000163", "Pianoboy高至豪", "ALONE ON THE WAY", "http://localhost:8080/resource/music/ALONE ON THE WAY.mp3", "http://localhost:8080/resource/music/ALONE ON THE WAY.png", 0);
insert into Yy values("0000164", "Quiana", "Moon Without The Stars", "http://localhost:8080/resource/music/Moon Without The Stars.mp3", "http://localhost:8080/resource/music/Moon Without The Stars.jpg", 0);
insert into Yy values("0000165", "Rabpit", "SAIKA II", "http://localhost:8080/resource/music/SAIKA II.mp3", "http://localhost:8080/resource/music/SAIKA II.jpg", 0);
insert into Yy values("0000166", "Rabpit", "Saika", "http://localhost:8080/resource/music/Saika.mp3", "http://localhost:8080/resource/music/Saika.jpg", 0);
insert into Yy values("0000167", "RAM WIRE", "僕らの手には何もないけど、", "http://localhost:8080/resource/music/僕らの手には何もないけど、.mp3", "http://localhost:8080/resource/music/僕らの手には何もないけど、.jpg", 0);
insert into Yy values("0000168", "Ramin Djawadi", "Strings of Prisoners", "http://localhost:8080/resource/music/Strings of Prisoners.mp3", "http://localhost:8080/resource/music/Strings of Prisoners.png", 0);
insert into Yy values("0000169", "Rezonate", "Pump It!", "http://localhost:8080/resource/music/Pump It!.mp3", "http://localhost:8080/resource/music/Pump It!.jpg", 0);
insert into Yy values("0000170", "Rigël Theatre", "Little Red Train", "http://localhost:8080/resource/music/Little Red Train.mp3", "http://localhost:8080/resource/music/Little Red Train.jpg", 0);
insert into Yy values("0000171", "Rihanna", "Love The Way You Lie (Part II)", "http://localhost:8080/resource/music/Love The Way You Lie (Part II).mp3", "http://localhost:8080/resource/music/Love The Way You Lie (Part II).jpg", 0);
insert into Yy values("0000172", "Rihanna Eminem", "Love The Way You Lie (Part II)", "http://localhost:8080/resource/music/Love The Way You Lie (Part II).mp3", "http://localhost:8080/resource/music/Love The Way You Lie (Part II).jpg", 0);
insert into Yy values("0000173", "RippleTale", "时计仕挂けの梦人形", "http://localhost:8080/resource/music/时计仕挂けの梦人形.mp3", "http://localhost:8080/resource/music/时计仕挂けの梦人形.png", 0);
insert into Yy values("0000174", "Robert de Boron", "Chiru (Saisei no Uta)", "http://localhost:8080/resource/music/Chiru (Saisei no Uta).mp3", "http://localhost:8080/resource/music/Chiru (Saisei no Uta).png", 0);
insert into Yy values("0000175", "Ronald Jenkees", "Guitar Sound", "http://localhost:8080/resource/music/Guitar Sound.mp3", "http://localhost:8080/resource/music/Guitar Sound.jpg", 0);
insert into Yy values("0000176", "Rudebrat", "The Quick and the Dead (Original Mix)", "http://localhost:8080/resource/music/The Quick and the Dead (Original Mix).mp3", "http://localhost:8080/resource/music/The Quick and the Dead (Original Mix).png", 0);
insert into Yy values("0000177", "Rudebrat", "Whiskey Dream VIP (Original Mix)", "http://localhost:8080/resource/music/Whiskey Dream VIP (Original Mix).mp3", "http://localhost:8080/resource/music/Whiskey Dream VIP (Original Mix).png", 0);
insert into Yy values("0000178", "Ryan", "The Beginning", "http://localhost:8080/resource/music/The Beginning.mp3", "http://localhost:8080/resource/music/The Beginning.jpg", 0);
insert into Yy values("0000179", "Ryan Farish", "Gentle Heart", "http://localhost:8080/resource/music/Gentle Heart.mp3", "http://localhost:8080/resource/music/Gentle Heart.png", 0);
insert into Yy values("0000180", "Said The Sky", "listen", "http://localhost:8080/resource/music/listen.mp3", "http://localhost:8080/resource/music/listen.jpg", 0);
insert into Yy values("0000181", "sasakure.UK", "uzumakinoharu", "http://localhost:8080/resource/music/uzumakinoharu.mp3", "http://localhost:8080/resource/music/uzumakinoharu.png", 0);
insert into Yy values("0000182", "Senpai Kondor", "Tomorrow With You", "http://localhost:8080/resource/music/Tomorrow With You.mp3", "http://localhost:8080/resource/music/Tomorrow With You.jpg", 0);
insert into Yy values("0000183", "Sensitive Bogdan Bondarenko", "Remember (Original Mix)", "http://localhost:8080/resource/music/Remember (Original Mix).mp3", "http://localhost:8080/resource/music/Remember (Original Mix).jpg", 0);
insert into Yy values("0000184", "Serafin", "어린왕자", "http://localhost:8080/resource/music/어린왕자.mp3", "http://localhost:8080/resource/music/어린왕자.jpg", 0);
insert into Yy values("0000185", "Seraph", "Zero［Instrumental］", "http://localhost:8080/resource/music/Zero［Instrumental］.mp3", "http://localhost:8080/resource/music/Zero［Instrumental］.jpg", 0);
insert into Yy values("0000186", "Sereno", "ASpiral Moon", "http://localhost:8080/resource/music/ASpiral Moon.mp3", "http://localhost:8080/resource/music/ASpiral Moon.png", 0);
insert into Yy values("0000187", "SILENT SIREN", "secret base ~君がくれたもの~", "http://localhost:8080/resource/music/secret base ~君がくれたもの~.mp3", "http://localhost:8080/resource/music/secret base ~君がくれたもの~.jpg", 0);
insert into Yy values("0000188", "Simply Three", "Counting Stars", "http://localhost:8080/resource/music/Counting Stars.mp3", "http://localhost:8080/resource/music/Counting Stars.jpg", 0);
insert into Yy values("0000189", "SNH48", "酷跑Run To You", "http://localhost:8080/resource/music/酷跑Run To You.mp3", "http://localhost:8080/resource/music/酷跑Run To You.jpg", 0);
insert into Yy values("0000190", "Stahl! Alex Skrindo", "Delightful (Original Mix)", "http://localhost:8080/resource/music/Delightful (Original Mix).mp3", "http://localhost:8080/resource/music/Delightful (Original Mix).jpg", 0);
insert into Yy values("0000191", "Teminite", "Get Down", "http://localhost:8080/resource/music/Get Down.mp3", "http://localhost:8080/resource/music/Get Down.jpg", 0);
insert into Yy values("0000192", "Tez Cadey", "Seve (1)", "http://localhost:8080/resource/music/Seve (1).mp3", "http://localhost:8080/resource/music/Seve (1).jpg", 0);
insert into Yy values("0000193", "Tez Cadey", "Seve", "http://localhost:8080/resource/music/Seve.mp3", "http://localhost:8080/resource/music/Seve.jpg", 0);
insert into Yy values("0000194", "The Standard Club", "LONGING LOVE (カバー)", "http://localhost:8080/resource/music/LONGING LOVE (カバー).mp3", "http://localhost:8080/resource/music/LONGING LOVE (カバー).png", 0);
insert into Yy values("0000195", "The Wanted", "Glad You Came", "http://localhost:8080/resource/music/Glad You Came.mp3", "http://localhost:8080/resource/music/Glad You Came.jpg", 0);
insert into Yy values("0000196", "The Weeknd", "Can't Feel My Face", "http://localhost:8080/resource/music/Can't Feel My Face.mp3", "http://localhost:8080/resource/music/Can't Feel My Face.jpg", 0);
insert into Yy values("0000197", "Thomas Greenberg", "The Right Path (1)", "http://localhost:8080/resource/music/The Right Path (1).mp3", "http://localhost:8080/resource/music/The Right Path (1).png", 0);
insert into Yy values("0000198", "Timmy Trumpet", "Nightmare", "http://localhost:8080/resource/music/Nightmare.mp3", "http://localhost:8080/resource/music/Nightmare.jpg", 0);
insert into Yy values("0000199", "Tobu", "Echoes", "http://localhost:8080/resource/music/Echoes.mp3", "http://localhost:8080/resource/music/Echoes.jpg", 0);
insert into Yy values("0000200", "Tobu", "Higher", "http://localhost:8080/resource/music/Higher.mp3", "http://localhost:8080/resource/music/Higher.jpg", 0);
insert into Yy values("0000201", "Tobu", "Morning Energy", "http://localhost:8080/resource/music/Morning Energy.mp3", "http://localhost:8080/resource/music/Morning Energy.jpg", 0);
insert into Yy values("0000202", "Tobu Marcus Mouya", "Running Away［NCS Release］", "http://localhost:8080/resource/music/Running Away［NCS Release］.mp3", "http://localhost:8080/resource/music/Running Away［NCS Release］.jpg", 0);
insert into Yy values("0000203", "TomLeevis", "The Top (Original Mix)", "http://localhost:8080/resource/music/The Top (Original Mix).mp3", "http://localhost:8080/resource/music/The Top (Original Mix).jpg", 0);
insert into Yy values("0000204", "Trifect", "Sky", "http://localhost:8080/resource/music/Sky.mp3", "http://localhost:8080/resource/music/Sky.jpg", 0);
insert into Yy values("0000205", "Truong Quynh Anh", "Don Coi (Instrumental)", "http://localhost:8080/resource/music/Don Coi (Instrumental).mp3", "http://localhost:8080/resource/music/Don Coi (Instrumental).jpg", 0);
insert into Yy values("0000206", "V.A.", "Sub Title", "http://localhost:8080/resource/music/Sub Title.mp3", "http://localhost:8080/resource/music/Sub Title.jpg", 0);
insert into Yy values("0000207", "V.K克", "Hua Sui Yue", "http://localhost:8080/resource/music/Hua Sui Yue.mp3", "http://localhost:8080/resource/music/Hua Sui Yue.jpg", 0);
insert into Yy values("0000208", "V.K克", "Paper Plane's Adventure", "http://localhost:8080/resource/music/Paper Plane's Adventure.mp3", "http://localhost:8080/resource/music/Paper Plane's Adventure.jpg", 0);
insert into Yy values("0000209", "V.K克", "Reflection(Mirror night)", "http://localhost:8080/resource/music/Reflection(Mirror night).mp3", "http://localhost:8080/resource/music/Reflection(Mirror night).jpg", 0);
insert into Yy values("0000210", "V.K克", "Wings Of Piano", "http://localhost:8080/resource/music/Wings Of Piano.mp3", "http://localhost:8080/resource/music/Wings Of Piano.jpg", 0);
insert into Yy values("0000211", "Valentin", "A Little Story", "http://localhost:8080/resource/music/A Little Story.mp3", "http://localhost:8080/resource/music/A Little Story.png", 0);
insert into Yy values("0000212", "Valentin", "One Sweetest", "http://localhost:8080/resource/music/One Sweetest.mp3", "http://localhost:8080/resource/music/One Sweetest.png", 0);
insert into Yy values("0000213", "Various Artists", "Pompeii (Krazy Kat Remix)", "http://localhost:8080/resource/music/Pompeii (Krazy Kat Remix).mp3", "http://localhost:8080/resource/music/Pompeii (Krazy Kat Remix).jpg", 0);
insert into Yy values("0000214", "Vindu", "Runaway", "http://localhost:8080/resource/music/Runaway.mp3", "http://localhost:8080/resource/music/Runaway.jpg", 0);
insert into Yy values("0000215", "Virtual Riot", "Energy Drink", "http://localhost:8080/resource/music/Energy Drink.mp3", "http://localhost:8080/resource/music/Energy Drink.jpg", 0);
insert into Yy values("0000216", "whtlook", "独行", "http://localhost:8080/resource/music/独行.mp3", "http://localhost:8080/resource/music/独行.jpg", 0);
insert into Yy values("0000217", "Worakls", "Bleu (Original Mix)", "http://localhost:8080/resource/music/Bleu (Original Mix).mp3", "http://localhost:8080/resource/music/Bleu (Original Mix).png", 0);
insert into Yy values("0000218", "WRLD", "Triumph", "http://localhost:8080/resource/music/Triumph.mp3", "http://localhost:8080/resource/music/Triumph.jpg", 0);
insert into Yy values("0000219", "X-Ray Dog", "String Tek", "http://localhost:8080/resource/music/String Tek.mp3", "http://localhost:8080/resource/music/String Tek.png", 0);
insert into Yy values("0000220", "Xenoglossy", "妖怪祭参道", "http://localhost:8080/resource/music/妖怪祭参道.mp3", "http://localhost:8080/resource/music/妖怪祭参道.jpg", 0);
insert into Yy values("0000221", "ZuXin Utsuro", "月下桜天國", "http://localhost:8080/resource/music/月下桜天國.mp3", "http://localhost:8080/resource/music/月下桜天國.jpg", 0);
insert into Yy values("0000222", "α·Pav", "Princess", "http://localhost:8080/resource/music/Princess.mp3", "http://localhost:8080/resource/music/Princess.png", 0);
insert into Yy values("0000223", "いきものがかり", "ハルウタ", "http://localhost:8080/resource/music/ハルウタ.mp3", "http://localhost:8080/resource/music/ハルウタ.png", 0);
insert into Yy values("0000224", "おさむらいさん", "セツナトリップ (1)", "http://localhost:8080/resource/music/セツナトリップ (1).mp3", "http://localhost:8080/resource/music/セツナトリップ (1).jpg", 0);
insert into Yy values("0000225", "おさむらいさん", "セツナトリップ", "http://localhost:8080/resource/music/セツナトリップ.mp3", "http://localhost:8080/resource/music/セツナトリップ.jpg", 0);
insert into Yy values("0000226", "おさむらいさん", "千本桜 (1)", "http://localhost:8080/resource/music/千本桜 (1).mp3", "http://localhost:8080/resource/music/千本桜 (1).jpg", 0);
insert into Yy values("0000227", "おさむらいさん", "千本桜", "http://localhost:8080/resource/music/千本桜.mp3", "http://localhost:8080/resource/music/千本桜.jpg", 0);
insert into Yy values("0000228", "のぶなが", "深海少女", "http://localhost:8080/resource/music/深海少女.mp3", "http://localhost:8080/resource/music/深海少女.jpg", 0);
insert into Yy values("0000229", "ぽんきち", "百花魁と白徳利", "http://localhost:8080/resource/music/百花魁と白徳利.mp3", "http://localhost:8080/resource/music/百花魁と白徳利.jpg", 0);
insert into Yy values("0000230", "みかん箱 Foxtail-Grass Studio", "かわくだり", "http://localhost:8080/resource/music/かわくだり.mp3", "http://localhost:8080/resource/music/かわくだり.png", 0);
insert into Yy values("0000231", "らいらい", "失う", "http://localhost:8080/resource/music/失う.mp3", "http://localhost:8080/resource/music/失う.jpg", 0);
insert into Yy values("0000232", "れをる", "-nil- (1)", "http://localhost:8080/resource/music/-nil- (1).mp3", "http://localhost:8080/resource/music/-nil- (1).jpg", 0);
insert into Yy values("0000233", "れをる", "-nil-", "http://localhost:8080/resource/music/-nil-.mp3", "http://localhost:8080/resource/music/-nil-.jpg", 0);
insert into Yy values("0000234", "三亩地", "城南花已开", "http://localhost:8080/resource/music/城南花已开.mp3", "http://localhost:8080/resource/music/城南花已开.jpg", 0);
insert into Yy values("0000235", "三亩地", "寻", "http://localhost:8080/resource/music/寻.mp3", "http://localhost:8080/resource/music/寻.jpg", 0);
insert into Yy values("0000236", "中岛岬", "Lilac", "http://localhost:8080/resource/music/Lilac.mp3", "http://localhost:8080/resource/music/Lilac.png", 0);
insert into Yy values("0000237", "伊戈尔.克鲁托伊", "Sad Angel", "http://localhost:8080/resource/music/Sad Angel.mp3", "http://localhost:8080/resource/music/Sad Angel.png", 0);
insert into Yy values("0000238", "佐橋俊彦", "ツナ覚醒", "http://localhost:8080/resource/music/ツナ覚醒.mp3", "http://localhost:8080/resource/music/ツナ覚醒.jpg", 0);
insert into Yy values("0000239", "倉木麻衣", "Time after time〜花舞う街で〜", "http://localhost:8080/resource/music/Time after time〜花舞う街で〜.mp3", "http://localhost:8080/resource/music/Time after time〜花舞う街で〜.png", 0);
insert into Yy values("0000240", "倉木麻衣", "渡月橋 ~君 想ふ~", "http://localhost:8080/resource/music/渡月橋 ~君 想ふ~.mp3", "http://localhost:8080/resource/music/渡月橋 ~君 想ふ~.jpg", 0);
insert into Yy values("0000241", "凛", "Ayakashi set 16 ~ さくらさくら", "http://localhost:8080/resource/music/Ayakashi set 16 ~ さくらさくら.mp3", "http://localhost:8080/resource/music/Ayakashi set 16 ~ さくらさくら.jpg", 0);
insert into Yy values("0000242", "削除", "Kronos", "http://localhost:8080/resource/music/Kronos.mp3", "http://localhost:8080/resource/music/Kronos.png", 0);
insert into Yy values("0000243", "削除 xi", "STORIA", "http://localhost:8080/resource/music/STORIA.mp3", "http://localhost:8080/resource/music/STORIA.jpg", 0);
insert into Yy values("0000244", "加賀谷玲", "One night (Instrumental Version)", "http://localhost:8080/resource/music/One night (Instrumental Version).mp3", "http://localhost:8080/resource/music/One night (Instrumental Version).png", 0);
insert into Yy values("0000245", "勝又隆一", "あなたを想いたい", "http://localhost:8080/resource/music/あなたを想いたい.mp3", "http://localhost:8080/resource/music/あなたを想いたい.jpg", 0);
insert into Yy values("0000246", "叶洛洛 西瓜JUN 知性的小方块 泥鳅Niko", "九九八十一", "http://localhost:8080/resource/music/九九八十一.mp3", "http://localhost:8080/resource/music/九九八十一.jpg", 0);
insert into Yy values("0000247", "呦猫UNEKO", "梦回还", "http://localhost:8080/resource/music/梦回还.mp3", "http://localhost:8080/resource/music/梦回还.jpg", 0);
insert into Yy values("0000248", "坂本昌一郎", "思い出をありがとう", "http://localhost:8080/resource/music/思い出をありがとう.mp3", "http://localhost:8080/resource/music/思い出をありがとう.jpg", 0);
insert into Yy values("0000249", "夏小舟", "Love home", "http://localhost:8080/resource/music/Love home.mp3", "http://localhost:8080/resource/music/Love home.jpg", 0);
insert into Yy values("0000250", "大石昌良", "君じゃなきゃダメみたい (instrumental)", "http://localhost:8080/resource/music/君じゃなきゃダメみたい (instrumental).mp3", "http://localhost:8080/resource/music/君じゃなきゃダメみたい (instrumental).jpg", 0);
insert into Yy values("0000251", "大石昌良", "君じゃなきゃダメみたい", "http://localhost:8080/resource/music/君じゃなきゃダメみたい.mp3", "http://localhost:8080/resource/music/君じゃなきゃダメみたい.jpg", 0);
insert into Yy values("0000252", "小池雅人", "リュウ.ハヤブサ 鮮烈のリュウ -DW SW MIX-", "http://localhost:8080/resource/music/リュウ.ハヤブサ 鮮烈のリュウ -DW SW MIX-.mp3", "http://localhost:8080/resource/music/リュウ.ハヤブサ 鮮烈のリュウ -DW SW MIX-.jpg", 0);
insert into Yy values("0000253", "小澤正澄", "attraction", "http://localhost:8080/resource/music/attraction.mp3", "http://localhost:8080/resource/music/attraction.png", 0);
insert into Yy values("0000254", "山下智久", "Loveless (Instrumental)", "http://localhost:8080/resource/music/Loveless (Instrumental).mp3", "http://localhost:8080/resource/music/Loveless (Instrumental).png", 0);
insert into Yy values("0000255", "张逸帆", "Canon Rock (1)", "http://localhost:8080/resource/music/Canon Rock (1).mp3", "http://localhost:8080/resource/music/Canon Rock (1).jpg", 0);
insert into Yy values("0000256", "徐梦圆", "Magic Piano", "http://localhost:8080/resource/music/Magic Piano.mp3", "http://localhost:8080/resource/music/Magic Piano.jpg", 0);
insert into Yy values("0000257", "徐梦圆", "孤龙山-主场景", "http://localhost:8080/resource/music/孤龙山-主场景.mp3", "http://localhost:8080/resource/music/孤龙山-主场景.jpg", 0);
insert into Yy values("0000258", "愛殺寶貝", "ふたりのきもちのほんとのひみつ(カラオケ)", "http://localhost:8080/resource/music/ふたりのきもちのほんとのひみつ(カラオケ).mp3", "http://localhost:8080/resource/music/ふたりのきもちのほんとのひみつ(カラオケ).jpg", 0);
insert into Yy values("0000259", "愛殺寶貝", "ふたりのきもちのほんとのひみつ", "http://localhost:8080/resource/music/ふたりのきもちのほんとのひみつ.mp3", "http://localhost:8080/resource/music/ふたりのきもちのほんとのひみつ.jpg", 0);
insert into Yy values("0000260", "折倉俊則", "if (piano arrange)", "http://localhost:8080/resource/music/if (piano arrange).mp3", "http://localhost:8080/resource/music/if (piano arrange).jpg", 0);
insert into Yy values("0000261", "文武贝", "繁华的寂静", "http://localhost:8080/resource/music/繁华的寂静.mp3", "http://localhost:8080/resource/music/繁华的寂静.jpg", 0);
insert into Yy values("0000262", "昼夜", "时空隧道 (1)", "http://localhost:8080/resource/music/时空隧道 (1).mp3", "http://localhost:8080/resource/music/时空隧道 (1).jpg", 0);
insert into Yy values("0000263", "昼夜", "樱花樱花想见你 (钢琴版)", "http://localhost:8080/resource/music/樱花樱花想见你 (钢琴版).mp3", "http://localhost:8080/resource/music/樱花樱花想见你 (钢琴版).jpg", 0);
insert into Yy values("0000264", "昼夜", "狐言 钢琴版", "http://localhost:8080/resource/music/狐言 钢琴版.mp3", "http://localhost:8080/resource/music/狐言 钢琴版.jpg", 0);
insert into Yy values("0000265", "木制みゅーと", "七つ柊水光", "http://localhost:8080/resource/music/七つ柊水光.mp3", "http://localhost:8080/resource/music/七つ柊水光.jpg", 0);
insert into Yy values("0000266", "未泯", "Miss You", "http://localhost:8080/resource/music/Miss You.mp3", "http://localhost:8080/resource/music/Miss You.jpg", 0);
insert into Yy values("0000267", "李玉刚", "刚好遇见你", "http://localhost:8080/resource/music/刚好遇见你.mp3", "http://localhost:8080/resource/music/刚好遇见你.jpg", 0);
insert into Yy values("0000268", "松本梨香", "めざせポケモンマスター(2)", "http://localhost:8080/resource/music/めざせポケモンマスター(2).mp3", "http://localhost:8080/resource/music/めざせポケモンマスター(2).png", 0);
insert into Yy values("0000269", "松本梨香", "めざせポケモンマスター", "http://localhost:8080/resource/music/めざせポケモンマスター.mp3", "http://localhost:8080/resource/music/めざせポケモンマスター.png", 0);
insert into Yy values("0000270", "桂木", "Dynamix 主界面BGM (1)", "http://localhost:8080/resource/music/Dynamix 主界面BGM (1).mp3", "http://localhost:8080/resource/music/Dynamix 主界面BGM (1).jpg", 0);
insert into Yy values("0000271", "桂木", "Dynamix 主界面BGM", "http://localhost:8080/resource/music/Dynamix 主界面BGM.mp3", "http://localhost:8080/resource/music/Dynamix 主界面BGM.jpg", 0);
insert into Yy values("0000272", "桂木", "Keep Out - TangJuan (1)", "http://localhost:8080/resource/music/Keep Out - TangJuan (1).mp3", "http://localhost:8080/resource/music/Keep Out - TangJuan (1).png", 0);
insert into Yy values("0000273", "桂木", "Keep Out - TangJuan", "http://localhost:8080/resource/music/Keep Out - TangJuan.mp3", "http://localhost:8080/resource/music/Keep Out - TangJuan.png", 0);
insert into Yy values("0000274", "桂木", "Mystic Night - U咲 (1)", "http://localhost:8080/resource/music/Mystic Night - U咲 (1).mp3", "http://localhost:8080/resource/music/Mystic Night - U咲 (1).png", 0);
insert into Yy values("0000275", "桂木", "Mystic Night - U咲", "http://localhost:8080/resource/music/Mystic Night - U咲.mp3", "http://localhost:8080/resource/music/Mystic Night - U咲.png", 0);
insert into Yy values("0000276", "桂木", "REconstruction - Ryazan (1)", "http://localhost:8080/resource/music/REconstruction - Ryazan (1).mp3", "http://localhost:8080/resource/music/REconstruction - Ryazan (1).png", 0);
insert into Yy values("0000277", "桂木", "REconstruction - Ryazan", "http://localhost:8080/resource/music/REconstruction - Ryazan.mp3", "http://localhost:8080/resource/music/REconstruction - Ryazan.png", 0);
insert into Yy values("0000278", "桂木", "Stardust - mmry (1)", "http://localhost:8080/resource/music/Stardust - mmry (1).mp3", "http://localhost:8080/resource/music/Stardust - mmry (1).jpg", 0);
insert into Yy values("0000279", "桂木", "Stardust - mmry", "http://localhost:8080/resource/music/Stardust - mmry.mp3", "http://localhost:8080/resource/music/Stardust - mmry.jpg", 0);
insert into Yy values("0000280", "桂木", "【Arcaea】PRAGMATISM - Laur (1)", "http://localhost:8080/resource/music/【Arcaea】PRAGMATISM - Laur (1).mp3", "http://localhost:8080/resource/music/【Arcaea】PRAGMATISM - Laur (1).png", 0);
insert into Yy values("0000281", "桂木", "【Arcaea】PRAGMATISM - Laur", "http://localhost:8080/resource/music/【Arcaea】PRAGMATISM - Laur.mp3", "http://localhost:8080/resource/music/【Arcaea】PRAGMATISM - Laur.png", 0);
insert into Yy values("0000282", "河图 洛天依", "狐言", "http://localhost:8080/resource/music/狐言.mp3", "http://localhost:8080/resource/music/狐言.jpg", 0);
insert into Yy values("0000283", "洛天依 乌龟Sui", "权御天下", "http://localhost:8080/resource/music/权御天下.mp3", "http://localhost:8080/resource/music/权御天下.jpg", 0);
insert into Yy values("0000284", "流派未確定", "宴", "http://localhost:8080/resource/music/宴.mp3", "http://localhost:8080/resource/music/宴.png", 0);
insert into Yy values("0000285", "流派未確定", "眠りの吸血鬼", "http://localhost:8080/resource/music/眠りの吸血鬼.mp3", "http://localhost:8080/resource/music/眠りの吸血鬼.png", 0);
insert into Yy values("0000286", "浜口史郎", "ルフィ猛攻!", "http://localhost:8080/resource/music/ルフィ猛攻!.mp3", "http://localhost:8080/resource/music/ルフィ猛攻!.jpg", 0);
insert into Yy values("0000287", "浜口史郎", "追いつめられた", "http://localhost:8080/resource/music/追いつめられた.mp3", "http://localhost:8080/resource/music/追いつめられた.jpg", 0);
insert into Yy values("0000288", "漆柚", "封刀不为峥嵘", "http://localhost:8080/resource/music/封刀不为峥嵘.mp3", "http://localhost:8080/resource/music/封刀不为峥嵘.jpg", 0);
insert into Yy values("0000289", "澤和雄", "熱血!ストリートバスケット：：チーム選択", "http://localhost:8080/resource/music/熱血!ストリートバスケット：：チーム選択.mp3", "http://localhost:8080/resource/music/熱血!ストリートバスケット：：チーム選択.jpg", 0);
insert into Yy values("0000290", "澤和雄", "熱血!ストリートバスケット：：ナイアガラステージ", "http://localhost:8080/resource/music/熱血!ストリートバスケット：：ナイアガラステージ.mp3", "http://localhost:8080/resource/music/熱血!ストリートバスケット：：ナイアガラステージ.jpg", 0);
insert into Yy values("0000291", "澤和雄", "熱血!ストリートバスケット：：ハワイステージ", "http://localhost:8080/resource/music/熱血!ストリートバスケット：：ハワイステージ.mp3", "http://localhost:8080/resource/music/熱血!ストリートバスケット：：ハワイステージ.jpg", 0);
insert into Yy values("0000292", "澤和雄", "熱血!ストリートバスケット：：フロリダステージ", "http://localhost:8080/resource/music/熱血!ストリートバスケット：：フロリダステージ.mp3", "http://localhost:8080/resource/music/熱血!ストリートバスケット：：フロリダステージ.jpg", 0);
insert into Yy values("0000293", "澤和雄", "熱血!ストリートバスケット：：モード選択", "http://localhost:8080/resource/music/熱血!ストリートバスケット：：モード選択.mp3", "http://localhost:8080/resource/music/熱血!ストリートバスケット：：モード選択.jpg", 0);
insert into Yy values("0000294", "炫光动感", "Dynamix 主界面BGM (1)", "http://localhost:8080/resource/music/Dynamix 主界面BGM (1).mp3", "http://localhost:8080/resource/music/Dynamix 主界面BGM (1).png", 0);
insert into Yy values("0000295", "炫光动感", "Dynamix 主界面BGM", "http://localhost:8080/resource/music/Dynamix 主界面BGM.mp3", "http://localhost:8080/resource/music/Dynamix 主界面BGM.png", 0);
insert into Yy values("0000296", "無力P", "Frozen World", "http://localhost:8080/resource/music/Frozen World.mp3", "http://localhost:8080/resource/music/Frozen World.png", 0);
insert into Yy values("0000297", "爱内里菜&三枝夕夏", "七つの海を渡る风のように", "http://localhost:8080/resource/music/七つの海を渡る风のように.mp3", "http://localhost:8080/resource/music/七つの海を渡る风のように.png", 0);
insert into Yy values("0000298", "王力宏 章子怡", "爱一点", "http://localhost:8080/resource/music/爱一点.mp3", "http://localhost:8080/resource/music/爱一点.jpg", 0);
insert into Yy values("0000299", "甘雨", "So Beautiful", "http://localhost:8080/resource/music/So Beautiful.mp3", "http://localhost:8080/resource/music/So Beautiful.png", 0);
insert into Yy values("0000300", "甘雨", "You're My Angel", "http://localhost:8080/resource/music/You're My Angel.mp3", "http://localhost:8080/resource/music/You're My Angel.png", 0);
insert into Yy values("0000301", "甘雨", "올해도 니가 그리운 날", "http://localhost:8080/resource/music/올해도 니가 그리운 날.mp3", "http://localhost:8080/resource/music/올해도 니가 그리운 날.png", 0);
insert into Yy values("0000302", "申东辉 Nicode", "Loadstar", "http://localhost:8080/resource/music/Loadstar.mp3", "http://localhost:8080/resource/music/Loadstar.jpg", 0);
insert into Yy values("0000303", "石进", "夜的钢琴曲五", "http://localhost:8080/resource/music/夜的钢琴曲五.mp3", "http://localhost:8080/resource/music/夜的钢琴曲五.png", 0);
insert into Yy values("0000304", "神乃木製作所", "三年幻想郷", "http://localhost:8080/resource/music/三年幻想郷.mp3", "http://localhost:8080/resource/music/三年幻想郷.png", 0);
insert into Yy values("0000305", "福山潤", "dedicate", "http://localhost:8080/resource/music/dedicate.mp3", "http://localhost:8080/resource/music/dedicate.jpg", 0);
insert into Yy values("0000306", "米津玄師", "Lemon (1)", "http://localhost:8080/resource/music/Lemon (1).mp3", "http://localhost:8080/resource/music/Lemon (1).jpg", 0);
insert into Yy values("0000307", "羽肿", "City (1)", "http://localhost:8080/resource/music/City (1).mp3", "http://localhost:8080/resource/music/City (1).jpg", 0);
insert into Yy values("0000308", "羽肿", "Rain after Summer (1)", "http://localhost:8080/resource/music/Rain after Summer (1).mp3", "http://localhost:8080/resource/music/Rain after Summer (1).png", 0);
insert into Yy values("0000309", "羽肿", "花火が瞬く夜に (1)", "http://localhost:8080/resource/music/花火が瞬く夜に (1).mp3", "http://localhost:8080/resource/music/花火が瞬く夜に (1).png", 0);
insert into Yy values("0000310", "舞風", "夜桜街道 (instrumental)", "http://localhost:8080/resource/music/夜桜街道 (instrumental).mp3", "http://localhost:8080/resource/music/夜桜街道 (instrumental).png", 0);
insert into Yy values("0000311", "花澤香菜", "恋愛サーキュレーション(2)", "http://localhost:8080/resource/music/恋愛サーキュレーション(2).mp3", "http://localhost:8080/resource/music/恋愛サーキュレーション(2).png", 0);
insert into Yy values("0000312", "花澤香菜", "恋愛サーキュレーション", "http://localhost:8080/resource/music/恋愛サーキュレーション.mp3", "http://localhost:8080/resource/music/恋愛サーキュレーション.png", 0);
insert into Yy values("0000313", "英雄联盟", "Welcome to Planet Urf", "http://localhost:8080/resource/music/Welcome to Planet Urf.mp3", "http://localhost:8080/resource/music/Welcome to Planet Urf.jpg", 0);
insert into Yy values("0000314", "范钊达（ZD Van）", "Adventure", "http://localhost:8080/resource/music/Adventure.mp3", "http://localhost:8080/resource/music/Adventure.jpg", 0);
insert into Yy values("0000315", "赵海洋", "夜空的寂静", "http://localhost:8080/resource/music/夜空的寂静.mp3", "http://localhost:8080/resource/music/夜空的寂静.jpg", 0);
insert into Yy values("0000316", "逆时针向", "熹光", "http://localhost:8080/resource/music/熹光.mp3", "http://localhost:8080/resource/music/熹光.png", 0);
insert into Yy values("0000317", "遊助", "一笑懸命", "http://localhost:8080/resource/music/一笑懸命.mp3", "http://localhost:8080/resource/music/一笑懸命.jpg", 0);
insert into Yy values("0000318", "采风乐坊", "蓄势 ~GEAR UP~", "http://localhost:8080/resource/music/蓄势 ~GEAR UP~.mp3", "http://localhost:8080/resource/music/蓄势 ~GEAR UP~.png", 0);
insert into Yy values("0000319", "金致焕", "필살의 검Part 2", "http://localhost:8080/resource/music/필살의 검Part 2.mp3", "http://localhost:8080/resource/music/필살의 검Part 2.jpg", 0);
insert into Yy values("0000320", "闫东炜", "万吨匿名信", "http://localhost:8080/resource/music/万吨匿名信.mp3", "http://localhost:8080/resource/music/万吨匿名信.jpg", 0);
insert into Yy values("0000321", "闫东炜", "华灯爱", "http://localhost:8080/resource/music/华灯爱.mp3", "http://localhost:8080/resource/music/华灯爱.jpg", 0);
insert into Yy values("0000322", "闫东炜", "四叶草的幻想", "http://localhost:8080/resource/music/四叶草的幻想.mp3", "http://localhost:8080/resource/music/四叶草的幻想.png", 0);
insert into Yy values("0000323", "闫东炜", "極楽浄土-伴奏-埋葬.ver", "http://localhost:8080/resource/music/極楽浄土-伴奏-埋葬.ver.mp3", "http://localhost:8080/resource/music/極楽浄土-伴奏-埋葬.ver.jpg", 0);
insert into Yy values("0000324", "闫东炜", "简单与初夏", "http://localhost:8080/resource/music/简单与初夏.mp3", "http://localhost:8080/resource/music/简单与初夏.jpg", 0);
insert into Yy values("0000325", "闫东炜", "萤火虫の怨", "http://localhost:8080/resource/music/萤火虫の怨.mp3", "http://localhost:8080/resource/music/萤火虫の怨.jpg", 0);
insert into Yy values("0000326", "闫东炜", "萤火虫之愿(完整版)", "http://localhost:8080/resource/music/萤火虫之愿(完整版).mp3", "http://localhost:8080/resource/music/萤火虫之愿(完整版).png", 0);
insert into Yy values("0000327", "闫东炜", "蝉翼之音~", "http://localhost:8080/resource/music/蝉翼之音~.mp3", "http://localhost:8080/resource/music/蝉翼之音~.png", 0);
insert into Yy values("0000328", "闫东炜", "雪落与掌心 (1)", "http://localhost:8080/resource/music/雪落与掌心 (1).mp3", "http://localhost:8080/resource/music/雪落与掌心 (1).jpg", 0);
insert into Yy values("0000329", "闫东炜", "风屿", "http://localhost:8080/resource/music/风屿.mp3", "http://localhost:8080/resource/music/风屿.jpg", 0);
insert into Yy values("0000330", "闫东炜", "风屿（Wind Island) (1)", "http://localhost:8080/resource/music/风屿（Wind Island) (1).mp3", "http://localhost:8080/resource/music/风屿（Wind Island) (1).png", 0);
insert into Yy values("0000331", "闫东炜", "风屿（Wind Island)", "http://localhost:8080/resource/music/风屿（Wind Island).mp3", "http://localhost:8080/resource/music/风屿（Wind Island).jpg", 0);
insert into Yy values("0000332", "韩安旭", "多幸运", "http://localhost:8080/resource/music/多幸运.mp3", "http://localhost:8080/resource/music/多幸运.jpg", 0);
insert into Yy values("0000333", "饭碗的彼岸", "小夏，多变的天气如妳", "http://localhost:8080/resource/music/小夏，多变的天气如妳.mp3", "http://localhost:8080/resource/music/小夏，多变的天气如妳.jpg", 0);
insert into Yy values("0000334", "饭碗的彼岸", "小河", "http://localhost:8080/resource/music/小河.mp3", "http://localhost:8080/resource/music/小河.jpg", 0);
insert into Yy values("0000335", "饭碗的彼岸", "风居住的街道（Piano ver） (COVER：磯村由紀子）", "http://localhost:8080/resource/music/风居住的街道（Piano ver） (COVER：磯村由紀子）.mp3", "http://localhost:8080/resource/music/风居住的街道（Piano ver） (COVER：磯村由紀子）.jpg", 0);
insert into Yy values("0000336", "高野健一", "さくら", "http://localhost:8080/resource/music/さくら.mp3", "http://localhost:8080/resource/music/さくら.jpg", 0);
insert into Yy values('0000337', '丸子呦', '广寒宫', 'http://localhost:8080/resource/music/广寒宫.mp3', 'http://localhost:8080/resource/music/广寒宫.jpg', 0);
